### PR TITLE
Disable precompiled binaries on macOS, fix Android builds on macOS host, add and use TorStatus enum, and export SOCKSSocket class

### PR DESCRIPTION
**Pull request by sneurlax**
This succeeds #14 

Merge conflicts have attempted to be resolved.  tor_plugin_ffi.podspec may need to be renamed to tor.podspect--all platforms should be tested.  Platform testing is what's currently stopping me from [merging package name and author changes over](https://github.com/cypherstack/tor/pull/19) (and merge conflicts)

### CODE REVIEW

**Comment by icota** [comment]
@sneurlax is this missing `tor.dart`? Looking at the example code the interface obviously changed but I'm not seeing `torDataDirPath` or `TorStatus` in there?

**Comment by sneurlax** [comment]
> @sneurlax is this missing `tor.dart`? Looking at the example code the interface obviously changed but I'm not seeing `torDataDirPath` or `TorStatus` in there?

I'll update it if I botched the merge--totally possible.

**Comment by sneurlax** [comment]
I thought I'd be able to focus on this but I'll have to give it another whack another time.

Basically just pull the macos-related cargokit changes if you want to disable the [binary shipped for macos](https://github.com/Foundation-Devices/tor/blob/main/macos/libtor_ffi_plugin.dylib)

**Comment by sneurlax** [comment]
https://github.com/Foundation-Devices/tor/pull/20 implemented the cargokit update that was the main reason for this PR!

**Pull request closed without merging**
