### PR TITLE
Change plugin name and author

### PR DESCRIPTION
**Pull request by icota**
`tor_ffi_plugin` is kind of wordy and template-y. It doesn't reflect the grand ambitions this project has.

### CODE REVIEW

**Comment by icota** [comment]
@sneurlax I hope you guys don't mind! `tor` is what it used to be before we FFI'd it and IMO it's a much better name with regards to #2

**Comment by icota** [comment]
I tested this change on Linux and Android and it was all fine

**Comment by sneurlax** [comment]
> @sneurlax I hope you guys don't mind! `tor` is what it used to be before we FFI'd it and IMO it's a much better name with regards to #2

hey don't git blame me :) the rename came alongside the cargokit refactor for which I can't take credit

**Comment by sneurlax** [comment]
it should be fine, there were just issues with cargokit being happy when a rename was tried before

**Pull request merged**
